import type { Metadata } from "next";
import ColorThemeToggle from "./_components/ColorThemeToggle";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const TEMPLATE = {
  title: "Personal Cloud Dashboard",
  subtitle:
    "Minimal overview of your infrastructure. Swap in real data later (k8s API / Prometheus / node exporter).",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b border-zinc-200 bg-white">
          <div className="mx-auto flex max-w-6xl flex-col gap-4 px-6 py-4 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <div className="text-sm font-semibold tracking-tight">
                {TEMPLATE.title}
              </div>
              <div className="mt-1 text-sm text-zinc-600">{TEMPLATE.subtitle}</div>
            </div>

            <div className="flex items-center gap-3">
              {/* Top-right: keep this clean */}
              <ColorThemeToggle />
              <button className="rounded-xl bg-zinc-900 px-3 py-2 text-sm text-white hover:bg-zinc-800">
                Login
              </button>
            </div>
          </div>
        </header>

        {children}
      </body>
    </html>
  );
}
